import * as THREE from 'three';
import {useMemo} from 'react';
export type V = [number,number,number];
export function texture(kind:'grass'|'paving'|'stone'|'wood') {
 const canvas=document.createElement('canvas');canvas.width=canvas.height=1024;const c=canvas.getContext('2d')!;
 let seed=123456;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
 const base=kind==='grass'?[80,105,44]:kind==='paving'?[156,159,150]:kind==='stone'?[179,176,161]:[111,83,50];
 const data=c.createImageData(1024,1024);for(let i=0;i<data.data.length;i+=4){const n=(rand()-.5)*(kind==='grass'?60:30);for(let j=0;j<3;j++)data.data[i+j]=base[j]+n;data.data[i+3]=255}c.putImageData(data,0,0);
 if(kind==='paving'||kind==='stone'){const step=kind==='paving'?256:128;for(let y=0;y<1024;y+=step){const offset=(y/step)%2*step/2;for(let x=-step;x<1024;x+=step){c.strokeStyle='#5b62564d';c.lineWidth=5;c.strokeRect(x+offset,y,step,step);c.strokeStyle='#e6e3d65e';c.lineWidth=2;c.strokeRect(x+offset+4,y+4,step-8,step-8)}}}
 if(kind==='grass'){for(let i=0;i<28000;i++){let x=rand()*1024,y=rand()*1024;c.strokeStyle=i%2?'#93a05d80':'#2d491c70';c.lineWidth=.6+rand();c.beginPath();c.moveTo(x,y);c.lineTo(x+(rand()-.5)*5,y-rand()*9);c.stroke()}}
 if(kind==='wood'){for(let i=0;i<450;i++){c.strokeStyle=i%2?'#dbc79933':'#31221633';c.beginPath();const y=rand()*1024;c.moveTo(0,y);c.bezierCurveTo(300,y+rand()*15,700,y-rand()*20,1024,y);c.stroke()}}
 const t=new THREE.CanvasTexture(canvas);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;
}
const palette=new Map<string,THREE.MeshStandardMaterial>();
export function mat(color:string,metal=0){const key=color+metal;if(!palette.has(key))palette.set(key,new THREE.MeshStandardMaterial({color,roughness:metal?.32:.78,metalness:metal}));return palette.get(key)!}
export function Ball({at=[0,0,0],scale=1,color='#71834b',metal=0}:{at?:V;scale?:number|V;color?:string;metal?:number}){return <mesh position={at} scale={scale} castShadow receiveShadow material={mat(color,metal)}><sphereGeometry args={[1,24,16]}/></mesh>}
export function Box({at=[0,0,0],size=[1,1,1],color='#8e846d',rotation=[0,0,0],metal=0}:{at?:V;size?:V;color?:string;rotation?:V;metal?:number}){return <mesh position={at} rotation={rotation} castShadow receiveShadow material={mat(color,metal)}><boxGeometry args={size}/></mesh>}
export function Cylinder({at=[0,0,0],r=.1,top,h=1,color='#374b38',rotation=[0,0,0],metal=0}:{at?:V;r?:number;top?:number;h?:number;color?:string;rotation?:V;metal?:number}){return <mesh position={at} rotation={rotation} castShadow receiveShadow material={mat(color,metal)}><cylinderGeometry args={[top??r,r,h,32]}/></mesh>}
export function Ring({at=[0,0,0],r=1,tube=.04,color='#b7aa79',rotation=[Math.PI/2,0,0],metal=.65}:{at?:V;r?:number;tube?:number;color?:string;rotation?:V;metal?:number}){return <mesh position={at} rotation={rotation} material={mat(color,metal)} castShadow><torusGeometry args={[r,tube,10,64]}/></mesh>}
export function Sign({title,subtitle='',width=1.7,height=.65,at=[0,0,0],dark=true}:{title:string;subtitle?:string;width?:number;height?:number;at?:V;dark?:boolean}){const map=useMemo(()=>{const c=document.createElement('canvas');c.width=1024;c.height=384;const x=c.getContext('2d')!;x.fillStyle=dark?'#1d352d':'#e9e3cd';x.fillRect(0,0,1024,384);x.strokeStyle=dark?'#bbaa78':'#7e805e';x.lineWidth=3;x.strokeRect(16,16,992,352);x.textAlign='center';x.fillStyle=dark?'#eee5c9':'#263d30';x.font=`600 ${title.length>20?49:64}px Georgia`;x.fillText(title,512,subtitle?175:218);if(subtitle){x.fillStyle=dark?'#b7c6a7':'#627254';x.font='25px sans-serif';x.fillText(subtitle.toUpperCase(),512,254)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t},[title,subtitle,dark]);return <mesh position={at}><planeGeometry args={[width,height]}/><meshStandardMaterial map={map} roughness={.6}/></mesh>}
export function Glass({at=[0,0,0],size=[1,1,1]}:{at?:V;size?:V}){return <mesh position={at}><boxGeometry args={size}/><meshPhysicalMaterial color='#bad6d1' metalness={.05} roughness={.08} transmission={.65} transparent opacity={.45} thickness={.06} ior={1.45} envMapIntensity={1.5} depthWrite={false}/></mesh>}
export function Bench(){return <group>{Array.from({length:6},(_,i)=><Box key={'s'+i} at={[0,.55,-.27+i*.115]} size={[2,.085,.08]} color='#35533c' metal={.25}/>)}{Array.from({length:4},(_,i)=><Box key={'b'+i} at={[0,.82+i*.14,-.35]} size={[2,.095,.07]} color='#35533c' metal={.25}/>)}{[-.8,.8].map(x=><group key={x}><Box at={[x,.3,-.2]} size={[.09,.6,.1]} color='#1e3027' metal={.7}/><Box at={[x,.28,.22]} size={[.09,.55,.1]} color='#1e3027' metal={.7}/><Box at={[x,1,-.4]} size={[.08,.7,.08]} color='#1e3027' metal={.7}/><Box at={[x,.85,.05]} size={[.09,.075,.55]} color='#1e3027' metal={.7}/></group>)}</group>}
