import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Environment,Lightformer,PerformanceMonitor,Sky} from '@react-three/drei';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {stops,route,exhibitPosition} from './data';
import {Ball,Box,Cylinder,Ring} from './sceneAssets';
import {walkingShot,exhibitShot} from './cameraPath';
import ParkEnvironment from './ParkEnvironment';
import Exhibit from './Exhibits';
export type CameraMode='walk'|'focus'|'inspect'|'return';
function Director({target,actual,active,reduced,paused,onReady,onMode}:{target:React.RefObject<number>;actual:React.RefObject<number>;active:string|null;reduced:boolean;paused:boolean;onReady:(id:string)=>void;onMode:(mode:CameraMode)=>void}){
 const {camera,size}=useThree();const mode=useRef<CameraMode>('walk');const previous=useRef<string|null>(null);const look=useRef(walkingShot(target.current,size.width<700).look);const initialized=useRef(false);
 useFrame((_,delta)=>{const dt=Math.min(delta,.05);if(previous.current!==active){mode.current=active?'focus':'return';onMode(mode.current);previous.current=active}
 if(!active&&mode.current==='walk'&&!paused)actual.current=reduced?target.current:THREE.MathUtils.damp(actual.current,target.current,14,dt);
 const shot=active?exhibitShot(active,size.width<700):walkingShot(actual.current,size.width<700);
 const rate=reduced||!initialized.current?1:1-Math.exp(-(mode.current==='walk'?7:4.8)*dt);
 camera.position.lerp(shot.position,rate);look.current.lerp(shot.look,rate);const perspective=camera as THREE.PerspectiveCamera;perspective.fov=THREE.MathUtils.lerp(perspective.fov,shot.fov,rate);perspective.updateProjectionMatrix();camera.lookAt(look.current);initialized.current=true;
 if(camera.position.distanceTo(shot.position)<.055&&look.current.distanceTo(shot.look)<.035){if(mode.current==='focus'&&active){mode.current='inspect';onMode('inspect');onReady(active)}else if(mode.current==='return'){mode.current='walk';onMode('walk')}}
 });return null;
}
function Character({progress,active,reduced}:{progress:React.RefObject<number>;active:string|null;reduced:boolean}){
 const {camera}=useThree();const root=useRef<THREE.Group>(null);const limbs=useRef<(THREE.Group|null)[]>([]);const last=useRef(progress.current);const phase=useRef(0);const heading=useRef(new THREE.Quaternion());
 useFrame((_,dt)=>{if(!root.current)return;const p=progress.current;const v=route(p);root.current.position.set(...v);root.current.visible=!active||camera.position.distanceTo(root.current.position)>3.2;let direction=walkingShot(p).forward;if(active){const stop=stops.find(s=>s.id===active)!;direction=new THREE.Vector3(...exhibitPosition(stop.progress)).sub(root.current.position).normalize()}heading.current.setFromAxisAngle(new THREE.Vector3(0,1,0),Math.atan2(direction.x,direction.z));root.current.quaternion.slerp(heading.current,reduced?1:1-Math.exp(-10*dt));const moving=Math.abs(p-last.current)>.000002;phase.current+=Math.abs(p-last.current)*260;limbs.current.forEach((l,i)=>{if(l){const angle=active&&i===3?-.45:!reduced&&moving?Math.sin(phase.current+((i%2)+(i>=2?1:0))*Math.PI)*(i<2?.48:.32):0;l.rotation.x=THREE.MathUtils.damp(l.rotation.x,angle,20,dt)}});last.current=p;});
 return <group ref={root}><mesh position={[0,1.25,0]} castShadow><capsuleGeometry args={[.24,.36,8,16]}/><meshStandardMaterial color='#2d6359' roughness={.9}/></mesh><Box at={[0,1.23,.225]} size={[.18,.52,.04]} color='#dfd7c1'/>{[-.15,.15].map(x=><Box key={x} at={[x,1.27,.21]} size={[.09,.53,.055]} color='#3b7867'/>)}<Cylinder at={[0,1.64,0]} r={.09} h={.16} color='#bc8a68'/><Ball at={[0,1.87,0]} scale={[.23,.28,.23]} color='#b98969'/><Ball at={[0,2.04,-.035]} scale={[.245,.18,.24]} color='#302b28'/>{Array.from({length:8},(_,i)=><Ball key={i} at={[Math.sin(i*2.4)*.17,2.1+(i%2)*.04,Math.cos(i*2.4)*.15]} scale={.09} color='#302b28'/>)}{[-.09,.09].map(x=><Ball key={x} at={[x,1.89,.21]} scale={.025} color='#272b22'/>)}<Box at={[0,1.28,-.28]} size={[.38,.48,.19]} color='#b59765'/><Box at={[0,1.15,-.39]} size={[.27,.17,.04]} color='#927b55'/>{[-.16,.16].map(x=><Box key={x} at={[x,1.4,-.18]} size={[.04,.47,.06]} color='#3b3e2e'/>)}{[-1,1].map((s,i)=><group key={s}><group ref={r=>{limbs.current[i]=r}} position={[s*.14,.95,0]}><mesh position={[0,-.32,0]} castShadow><capsuleGeometry args={[.095,.5,6,12]}/><meshStandardMaterial color='#303a38'/></mesh><Box at={[0,-.76,.085]} size={[.18,.14,.34]} color='#d8d3bf'/><Box at={[0,-.82,.09]} size={[.2,.045,.36]} color='#a6a492'/></group><group ref={r=>{limbs.current[i+2]=r}} position={[s*.31,1.5,0]}><mesh position={[0,-.23,0]} castShadow><capsuleGeometry args={[.085,.34,6,12]}/><meshStandardMaterial color='#326a5b'/></mesh><Ball at={[0,-.51,0]} scale={[.075,.115,.075]} color='#b98969'/></group></group>)}</group>
}
export default function World({target,active,onOpen,reduced,overview,onReady,onMode}:{target:React.RefObject<number>;active:string|null;onOpen:(id:string)=>void;reduced:boolean;overview:boolean;onReady:(id:string)=>void;onMode:(mode:CameraMode)=>void}){
 const actual=useRef(target.current);const [low,setLow]=useState(innerWidth<700);const [visible,setVisible]=useState(!document.hidden);
 useEffect(()=>{const f=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f)},[]);
 return <Canvas shadows dpr={low?1:[1,1.75]} frameloop={visible?'always':'never'} camera={{position:walkingShot(target.current).position.toArray(),fov:53,near:.1,far:150}} gl={{antialias:true,powerPreference:'high-performance',toneMapping:THREE.ACESFilmicToneMapping}} onCreated={({gl})=>{gl.setClearColor('#bfd0c7');gl.toneMappingExposure=1.05}}><PerformanceMonitor bounds={()=>[24,52]} flipflops={2} onDecline={()=>setLow(true)}/><ambientLight intensity={.35}/><hemisphereLight args={['#dce9ee','#59613c',1]}/><directionalLight position={[-15,25,8]} intensity={3.1} color='#fff0cf' castShadow shadow-mapSize={low?[1024,1024]:[2048,2048]} shadow-camera-left={-23} shadow-camera-right={23} shadow-camera-top={23} shadow-camera-bottom={-23} shadow-camera-far={70} shadow-bias={-.00015} shadow-normalBias={.035}/><Sky distance={450000} sunPosition={[-15,25,8]} inclination={.55} azimuth={.25} turbidity={3} rayleigh={.7}/><fog attach="fog" args={['#c6d2bc',35,80]}/><Environment resolution={64} frames={1}><Lightformer form="rect" intensity={2.5} position={[0,10,-10]} scale={[20,12,1]}/><Lightformer form="rect" intensity={1.3} color='#c7dbc6' position={[-10,3,0]} rotation={[0,Math.PI/2,0]} scale={[14,8,1]}/></Environment><Director target={target} actual={actual} active={active} reduced={reduced} paused={overview} onReady={onReady} onMode={onMode}/><ParkEnvironment low={low} reduced={reduced}/>{stops.map(s=><Exhibit key={s.id} stop={s} selected={active===s.id} near={Math.abs(target.current-s.progress)<.035} onOpen={onOpen} reduced={reduced}/>)}<Character progress={actual} active={active} reduced={reduced}/></Canvas>
}
